services:
  user-service:
    build:
      context: ../../TASK-MANAGER-APP-USER-SERVICE
      dockerfile: Dockerfile.app
    container_name: user-service-app
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/${USER_SERVICE_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${USER_SERVICE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
    depends_on:
      user-service-db:
        condition: service_healthy

  user-service-db:
    image: postgres:17
    container_name: user-service-db
    environment:
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_POSTGRES_USER} -d ${USER_SERVICE_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - user-service-pgdata:/var/lib/postgresql

volumes:
  user-service-pgdata:
